on:
  pull_request:
    branches:
    - master
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        platform:
        - c
        - js
        - wasm
        - wasi
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: adopt
    - if: ${{ matrix.platform == 'wasi' }}
      uses: bytecodealliance/actions/wasmtime/setup@v1
    - if: ${{ matrix.platform == 'wasi' }}
      run: |
        mkdir -p "$HOME/.wasmtime/bin/"
        echo 'wasmtime "$@"'> "$HOME/.wasmtime/bin/wasmtime"
        chmod +x "$HOME/.wasmtime/bin/wasmtime"
    - run: |
        platforms=("c" "js" "wasm" "wasi")
        args=()
        for v in "${platforms[@]}"
        do
          if [[ "${{ matrix.platform }}" != "$v" ]]; then
            args+=("-Pteavm.tests.${v}=false")
          fi
        done
        ./gradlew "${args[@]}" build
