on:
  pull_request:
    branches:
    - master
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        java:
        - 11
        - 17
        - 21
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: "${{ matrix.java }}"
        distribution: adopt
    - name: run tests
      run: |
        # TODO enable wasm, wasi and c tests
        ./gradlew \
          "-Pteavm.tests.js=true" \
          "-Pteavm.tests.c=false" \
          "-Pteavm.tests.wasm=false" \
          "-Pteavm.tests.wasi=false" \
          build
