on:
  pull_request:
    branches:
    - master
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        java:
        - 11
        - 17
        - 21
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: "${{ matrix.java }}"
        distribution: adopt
    - uses: bytecodealliance/actions/wasmtime/setup@v1
    - run: gcc --version
    - run: |
        mkdir -p "$HOME/.wasmtime/bin/"
        echo 'wasmtime "$@"'> "$HOME/.wasmtime/bin/wasmtime"
        chmod +x "$HOME/.wasmtime/bin/wasmtime"
    - run: ./gradlew
           "--no-daemon"
           "--no-configuration-cache"
           "-Pteavm.tests.optimized=true"
           "-Pteavm.tests.js=true"
           "-Pteavm.tests.c=false" # TODO enable C test
           "-Pteavm.tests.wasm=true"
           "-Pteavm.tests.wasi=true"
           "-Pteavm.junit.js.decodeStack=false"
           test
