on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: adopt
    - run: ./gradlew publishToMavenLocal
