on:
  pull_request:
    branches:
    - master
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: adopt
    - uses: bytecodealliance/actions/wasmtime/setup@v1
    - run: |
        mkdir -p "$HOME/.wasmtime/bin/"
        echo 'wasmtime "$@"'> "$HOME/.wasmtime/bin/wasmtime"
        chmod +x "$HOME/.wasmtime/bin/wasmtime"
    - name: run tests
      run: |
        ./gradlew \
          "-Pteavm.tests.js=false" \
          "-Pteavm.tests.c=true" \
          "-Pteavm.tests.wasm=false" \
          "-Pteavm.tests.wasi=false" \
          build
