on:
  pull_request:
    branches:
    - master
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 100
    strategy:
      fail-fast: false
      matrix:
        java:
        - 11
        - 17
        - 21
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: "${{ matrix.java }}"
        distribution: adopt
    - uses: bytecodealliance/actions/wasmtime/setup@v1
    - run: |
        mkdir -p "$HOME/.wasmtime/bin/"
        echo 'wasmtime "$@"'> "$HOME/.wasmtime/bin/wasmtime"
        chmod +x "$HOME/.wasmtime/bin/wasmtime"
    - name: run tests
      run: |
        # TODO enable wasm and c test
        ./gradlew \
          "-Pteavm.tests.js=true" \
          "-Pteavm.tests.c=false" \
          "-Pteavm.tests.wasm=false" \
          "-Pteavm.tests.wasi=true" \
          test
