on:
  pull_request:
    branches:
    - master
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        platform:
        - c
        - js
        - wasm
        - wasi
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: adopt
    - uses: gradle/gradle-build-action@v2
    - if: ${{ matrix.platform == 'wasi' }}
      uses: bytecodealliance/actions/wasmtime/setup@v1
    - if: ${{ matrix.platform == 'wasi' }}
      run: |
        mkdir -p "$HOME/.wasmtime/bin/"
        echo 'wasmtime "$@"'> "$HOME/.wasmtime/bin/wasmtime"
        chmod +x "$HOME/.wasmtime/bin/wasmtime"
    - run: sudo apt install gcc-13 g++-13
    - run: |
        export CC=/usr/bin/gcc-13
        export CXX=/usr/bin/g++-13
        gcc --version
        platforms=("c" "js" "wasm" "wasi")
        args=()
        for v in "${platforms[@]}"
        do
          if [[ "${{ matrix.platform }}" != "$v" ]]; then
            args+=("-Pteavm.tests.${v}=false")
          fi
        done
        echo "${args[@]}"
        ./gradlew "${args[@]}" build
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: "test-reports-${{ matrix.platform }}"
        path: "tests/build/reports/tests/test"
