on:
  pull_request:
    branches:
    - master
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        java:
        - 11
        - 17
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: "${{ matrix.java }}"
        distribution: adopt
    - uses: bytecodealliance/actions/wasmtime/setup@v1
    - run: |
        mkdir -p "$HOME/.wasmtime/bin/"
        echo 'wasmtime "$@"'> "$HOME/.wasmtime/bin/wasmtime"
        chmod +x "$HOME/.wasmtime/bin/wasmtime"
    - run: ./gradlew build --stacktrace
