on:
  pull_request:
    branches:
    - master
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        platform:
        - c
        - js
        - wasm
        - wasi
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: adopt
    - if: ${{ matrix.platform == 'wasi' }}
      uses: bytecodealliance/actions/wasmtime/setup@v1
    - if: ${{ matrix.platform == 'wasi' }}
      run: |
        mkdir -p "$HOME/.wasmtime/bin/"
        echo 'wasmtime "$@"'> "$HOME/.wasmtime/bin/wasmtime"
        chmod +x "$HOME/.wasmtime/bin/wasmtime"
    - if: ${{ matrix.platform == 'c' }}
      run: |
        ./gradlew \
          "-Pteavm.tests.js=false" \
          "-Pteavm.tests.wasm=false" \
          "-Pteavm.tests.wasi=false" \
          build
    - if: ${{ matrix.platform == 'js' }}
      run: |
        ./gradlew \
          "-Pteavm.tests.c=false" \
          "-Pteavm.tests.wasm=false" \
          "-Pteavm.tests.wasi=false" \
          build
    - if: ${{ matrix.platform == 'wasm' }}
      run: |
        ./gradlew \
          "-Pteavm.tests.js=false" \
          "-Pteavm.tests.c=false" \
          "-Pteavm.tests.wasi=false" \
          build
    - if: ${{ matrix.platform == 'wasi' }}
      run: |
        ./gradlew \
          "-Pteavm.tests.js=false" \
          "-Pteavm.tests.c=false" \
          "-Pteavm.tests.wasm=false" \
          build
